# Usar uma versão leve do Ubuntu como base
FROM ubuntu:22.04

# Instalar o curl e o Java necessário para o agente do Jenkins
RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

# Criar o diretório para o Jenkins
RUN mkdir /home/jenkins

# Adicionar um usuário não-root
#RUN useradd -m jenkins
#USER jenkins

# Definir o diretório de trabalho
WORKDIR /home/jenkins

# Definir variáveis de ambiente
#ENV JENKINS_URL=http://jenkins:8080/
#ENV JENKINS_SECRET=c7aeeee9d10e457a35c87ed55a67b6911a8283c97bd33b0ec65e7684185fb5cc
#ENV AGENT_NAME=HOME

# Definir o comando para iniciar o agente Jenkins
CMD ["java", "-jar", "agent.jar", "-url", "http://jenkins:8080/", "-secret", "c7aeeee9d10e457a35c87ed55a67b6911a8283c97bd33b0ec65e7684185fb5cc", "-name", "HOME", "-workDir", "/home/jenkins"]
