# Usar uma versão leve do Ubuntu como base
FROM ubuntu:latest

# Instalar o curl e o Java necessário para o agente do Jenkins
RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    openjdk-11-jre-headless \
    && rm -rf /var/lib/apt/lists/*

# Criar o diretório para o Jenkins
RUN mkdir /home/jenkins

# Definir o diretório de trabalho (opcional)
 WORKDIR /home/jenkins

# Definir o comando para iniciar o agente Jenkins
CMD ["java", "-jar", "agent.jar", "-url", "http://jenkins:8080", "-secret", "db8bd712cdad82eecf2c19f03135978d2dc47239dc4a75d2a961ffb561a2c409", "-name", "lnsat-minio-d02.sef.sc.gov.br", "-workDir", "/home/jenkins"]