# Usar uma versão leve do Ubuntu como base
FROM ubuntu:latest

# Instalar o curl e o Java necessário para o agente do Jenkins
RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    openjdk-11-jre-headless \
    && rm -rf /var/lib/apt/lists/*

# Criar o diretório para o Jenkins
RUN mkdir /home/jenkins

# Definir o diretório de trabalho (opcional)
 WORKDIR /home/jenkins

# Definir o comando para iniciar o agente Jenkins
CMD ["java", "-jar", "agent.jar", "-url", "http://jenkins:8080/", "-secret", "f6e05efa3996ce414e040557f1e8e567da9fe73a09e6cdd2a4cfabf22f4001bb", "-name", "Docker-ubuntu", "-workDir", "/home/jenkins"]
