version: '3.8'

services:
  github_runner:
    image: myoung34/github-runner:latest
    container_name: github_runner
    environment:
      ORG_RUNNER: "false"  # Altere para "true" se quiser o runner no nível da organização
      REPO_URL: "https://github.com/vianalima/lab-devops"
      RUNNER_NAME: "docker-runner"
      RUNNER_TOKEN: "A5HS5HFQYLPDIDJX6D5INT3G4LUGU"  # Token gerado nas configurações do GitHub
      RUNNER_WORKDIR: "/tmp/github-runner"
      LABELS: "self-hosted,Docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/
    networks:
      - devops_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - devops_network

  ansible:
    build: .
    container_name: ansible
    volumes:
      - ./ansible:/app  # Substitua pelo caminho correto
    networks:
      - devops_network

  ubuntu_lite:
    #image: ubuntu:latest  # Use uma versão leve do Ubuntu
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    container_name: ubuntu_lite
    tty: true  # Mantém o contêiner ativo
    volumes:
      - ./jenkins:/home/jenkins
    networks:
      - devops_network    

networks:
  devops_network:
    driver: bridge
